create table IF NOT EXISTS user (
  id int primary key auto_increment,
  email varchar(255),
  userName varchar(255)
);

-- DROP ALL
DROP TABLE IF EXISTS FIXTURE;
DROP TABLE IF EXISTS COMPETITION;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS COUNTRY;


-- COUNTRY
CREATE TABLE COUNTRY (
        ID          SERIAL
    ,   CODE        VARCHAR(3) NOT NULL
    ,   DESCRIPTION VARCHAR (50)
    ,   UNIQUE (CODE)
    ,   PRIMARY KEY (ID)
);

-- TEAM
CREATE TABLE TEAM (
        ID          SERIAL
    ,   CODE        VARCHAR(3) NOT NULL
    ,   NAME        VARCHAR(50) NOT NULL
    ,   COUNTRY  INT NOT NULL REFERENCES COUNTRY(ID)
    ,   UNIQUE (CODE, COUNTRY)
    ,   PRIMARY KEY (ID)
);

-- COMPETITION
CREATE TABLE COMPETITION (
        ID          SERIAL
    ,   CODE        VARCHAR(4) NOT NULL
    ,   DESCRIPTION VARCHAR (50)
    ,   COUNTRY     INT NOT NULL REFERENCES COUNTRY(ID)
    ,   SEASON     INT NOT NULL
    ,   START_AT    DATE
    ,   END_AT      DATE
    ,   UNIQUE (CODE, SEASON)
    ,   PRIMARY KEY (ID)
);

-- FIXTURE
CREATE TABLE FIXTURE (
        ID              SERIAL
    ,   COMPETITION     INT NOT NULL REFERENCES COMPETITION(ID)
    ,   DATE_SEASON    INT NOT NULL
    ,   DATE_FIXTURE    DATE
    ,   HOME_TEAM       INT NOT NULL REFERENCES TEAM(ID)
    ,   AWAY_TEAM       INT NOT NULL REFERENCES TEAM(ID)
    ,   HOME_GOALS_HT   INT
    ,   AWAY_GOALS_HT   INT
    ,   HOME_GOALS_FT   INT
    ,   AWAY_GOALS_FT   INT
    ,   UNIQUE (COMPETITION, DATE_SEASON, HOME_TEAM, AWAY_TEAM)
    ,   PRIMARY KEY (ID)        
);